fixed booking test

diff --git a/strajk-bowling/.github/workflows/deploy.yml b/strajk-bowling/.github/workflows/deploy.yml
--- a/strajk-bowling/.github/workflows/deploy.yml
+++ b/strajk-bowling/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: run tests and deploy
+name: CI/CD
 
 on:
   push:
@@ -8,32 +8,24 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
-        with:
-          node-version: 18
 
-      - name: Remove node_modules and package-lock.json
-        run: |
-          rm -rf node_modules
-          rm -f package-lock.json
-
-      - name: Install dependencies
+      - name: Install dependecies
         run: npm install
 
       - name: Run tests
-        run: npm run test
+        run: npm test
 
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-        
 
   check-coverage:
     runs-on: ubuntu-latest
@@ -46,20 +38,18 @@ jobs:
       - name: Check test coverage
         run: |
           if [ ! -f ./coverage/coverage-summary.json ]; then
-            echo "Coverage report not found!"
-            exit 1
+          echo "Coverage report not found!"
+          exit 1
           fi
 
           echo "Coverage report found"
 
           COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
-          echo "Test coverage is ${COVERAGE}%" 
+          echo "Test coverage is ${COVERAGE}%"
 
           if (( $(echo "$COVERAGE < 90" | bc -l) )); then
-            echo "Coverage (${COVERAGE}%) is below 90%"
-            exit 1
-          else
-            echo "Coverage (${COVERAGE}%) is above 90%, check passed"
+          echo "Test coverage is below 90%, cannot deploy."
+          exit 1
           fi
 
   deploy:
@@ -71,23 +61,21 @@ jobs:
       id-token: write
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
+      - uses: actions/checkout@v4
       - name: Install modules
-        run: npm install
+        run: cd strajk-bowling && npm install
 
       - name: Build dist
-        run: npm run build
+        run: cd strajk-bowling && npm run build
 
-      - name: Setup Pages
+      - name: Setup pages
         uses: actions/configure-pages@v3
 
       - name: Upload dist folder
         uses: actions/upload-pages-artifact@v1
         with:
-          path: ./dist
+          path: "./strajk-bowling/dist"
 
-      - name: Deploy to GitHub Pages
+      - name: Deploy to Github Pages
         id: deployment
         uses: actions/deploy-pages@v1
